name: Build and Screenshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Verwende Node.js Version 20

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Install http-server
        run: npm install -g http-server

      - name: Start the server
        run: |
          nohup http-server dist &
          sleep 5

      - name: Take a screenshot
        run: |
          npm install puppeteer
          node -e "
            const { setTimeout } = require('timers/promises');
            const puppeteer = require('puppeteer');
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('http://localhost:8080', { waitUntil: 'networkidle2' });

              // Extra wait time for embeds
              await setTimeout(20000); // 20 seconds

              await page.evaluate(async () => {
                await new Promise((resolve) => {
                  let totalHeight = 0;
                  const distance = 100;
                  const timer = setInterval(() => {
                    const scrollHeight = document.body.scrollHeight;
                    window.scrollBy(0, distance);
                    totalHeight += distance;

                    if (totalHeight >= scrollHeight) {
                      clearInterval(timer);
                      resolve();
                    }
                  }, 100);
                });
              });
              await page.screenshot({ path: 'screenshot.png', fullPage: true });
              await browser.close();
            })();
          "

      - name: Copy screenshot to repo
        run: |
          mv screenshot.png ./dist/screenshot.png

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md dist/screenshot.png -f
          git commit -m "update screenshot"
          git push
